import { theme } from "../types";
import { TopBar } from "./TopBar";

interface CloudResumePreviewProps {
	markdown: string;
	onBack: () => void;
	onRestart: () => void;
}

export function CloudResumePreview({
	markdown,
	onBack,
	onRestart,
}: CloudResumePreviewProps) {
	return (
		<box flexGrow={1} flexDirection="column" backgroundColor={theme.bgDark}>
			<TopBar
				title="Generated Resume"
				description="Your resume, generated by Codex using your ChatGPT subscription."
			/>

			<scrollbox
				focused
				style={{
					rootOptions: { backgroundColor: theme.bgDark },
					wrapperOptions: { flexGrow: 1 },
					viewportOptions: { padding: 2 },
				}}
			>
				<code
					code={markdown}
					language="markdown"
					backgroundColor={theme.bgDark}
				/>
			</scrollbox>
		</box>
	);
}
