"""Evidence persistence orchestration for analysis pipeline outputs."""

from __future__ import annotations

from datetime import date, datetime
from typing import Iterable

from sqlalchemy.orm import Session

from artifactminer.db.models import ProjectEvidence, RepoStat
from artifactminer.evidence.extractors import insights_to_evidence
from artifactminer.evidence.models import EvidenceItem
from artifactminer.skills.deep_analysis import Insight

MAX_AUTOGENERATED_EVIDENCE_PER_RUN = 15


def _normalize_token(value: str) -> str:
    """Normalize for case/whitespace-insensitive dedupe comparisons."""
    return " ".join(value.strip().split()).lower()


def _evidence_key(item_type: str, content: str) -> tuple[str, str]:
    return (_normalize_token(item_type), _normalize_token(content))


def persist_generated_evidence(
    db: Session,
    repo_stat_id: int,
    evidence_items: Iterable[EvidenceItem],
    *,
    max_items: int = MAX_AUTOGENERATED_EVIDENCE_PER_RUN,
    commit: bool = True,
) -> list[ProjectEvidence]:
    """Persist generated evidence with dedupe and per-run insert cap."""
    if not isinstance(db, Session):
        raise ValueError("db must be a SQLAlchemy Session")
    if max_items < 0:
        raise ValueError("max_items must be >= 0")
    if max_items == 0:
        return []

    if not db.query(RepoStat).filter(RepoStat.id == repo_stat_id).first():
        raise ValueError(f"RepoStat {repo_stat_id} does not exist")

    existing_rows = (
        db.query(ProjectEvidence.type, ProjectEvidence.content)
        .filter(ProjectEvidence.repo_stat_id == repo_stat_id)
        .all()
    )
    seen_keys = {_evidence_key(item_type, content) for item_type, content in existing_rows}

    created: list[ProjectEvidence] = []
    for item in evidence_items:
        if len(created) >= max_items:
            break

        item_type = (item.type or "").strip()
        content = (item.content or "").strip()
        if not item_type or not content:
            continue

        dedupe_key = _evidence_key(item_type, content)
        if dedupe_key in seen_keys:
            continue
        seen_keys.add(dedupe_key)

        source = (item.source or "").strip() or None
        row = ProjectEvidence(
            repo_stat_id=repo_stat_id,
            type=item_type,
            content=content,
            source=source,
            date=item.date,
        )
        db.add(row)
        created.append(row)

    if commit:
        db.commit()

    return created


def persist_insights_as_project_evidence(
    db: Session,
    repo_stat_id: int,
    insights: list[Insight],
    *,
    repo_last_commit: date | datetime | None = None,
    max_items: int = MAX_AUTOGENERATED_EVIDENCE_PER_RUN,
    commit: bool = True,
) -> list[ProjectEvidence]:
    """Convert insights to evidence rows and persist with dedupe/cap rules."""
    evidence_items = insights_to_evidence(
        insights,
        repo_last_commit=repo_last_commit,
    )
    return persist_generated_evidence(
        db=db,
        repo_stat_id=repo_stat_id,
        evidence_items=evidence_items,
        max_items=max_items,
        commit=commit,
    )
