"""Add cascade and relationships to new models

Revision ID: b30abc89d0a8
Revises: 3b3f297185db
Create Date: 2025-11-16 17:20:57.241365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b30abc89d0a8'
down_revision: Union[str, Sequence[str], None] = '3b3f297185db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Skip constraint alterations on SQLite, which lacks full ALTER support.
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_skill', 'project_skills', ['repo_stat_id', 'skill_id'])
    op.drop_constraint('project_skills_repo_stat_id_fkey', 'project_skills', type_='foreignkey')
    op.drop_constraint('project_skills_skill_id_fkey', 'project_skills', type_='foreignkey')
    op.create_foreign_key(
        'fk_project_skills_repo_stat_id',
        'project_skills',
        'repo_stats',
        ['repo_stat_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        'fk_project_skills_skill_id',
        'project_skills',
        'skills',
        ['skill_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_constraint('resume_items_repo_stat_id_fkey', 'resume_items', type_='foreignkey')
    op.create_foreign_key(
        'fk_resume_items_repo_stat_id',
        'resume_items',
        'repo_stats',
        ['repo_stat_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Skip constraint alterations on SQLite, which lacks full ALTER support.
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_resume_items_repo_stat_id', 'resume_items', type_='foreignkey')
    op.create_foreign_key(
        'resume_items_repo_stat_id_fkey',
        'resume_items',
        'repo_stats',
        ['repo_stat_id'],
        ['id'],
    )
    op.drop_constraint('fk_project_skills_repo_stat_id', 'project_skills', type_='foreignkey')
    op.drop_constraint('fk_project_skills_skill_id', 'project_skills', type_='foreignkey')
    op.drop_constraint('uq_project_skill', 'project_skills', type_='unique')
    op.create_foreign_key(
        'project_skills_repo_stat_id_fkey',
        'project_skills',
        'repo_stats',
        ['repo_stat_id'],
        ['id'],
    )
    op.create_foreign_key(
        'project_skills_skill_id_fkey',
        'project_skills',
        'skills',
        ['skill_id'],
        ['id'],
    )
    # ### end Alembic commands ###
