"""Add cascade and relationships to new models

Revision ID: b30abc89d0a8
Revises: 3b3f297185db
Create Date: 2025-11-16 17:20:57.241365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b30abc89d0a8'
down_revision: Union[str, Sequence[str], None] = '3b3f297185db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_skill', 'project_skills', ['repo_stat_id', 'skill_id'])
    op.drop_constraint(None, 'project_skills', type_='foreignkey')
    op.drop_constraint(None, 'project_skills', type_='foreignkey')
    op.create_foreign_key(None, 'project_skills', 'repo_stats', ['repo_stat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_skills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'resume_items', type_='foreignkey')
    op.create_foreign_key(None, 'resume_items', 'repo_stats', ['repo_stat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume_items', type_='foreignkey')
    op.create_foreign_key(None, 'resume_items', 'repo_stats', ['repo_stat_id'], ['id'])
    op.drop_constraint(None, 'project_skills', type_='foreignkey')
    op.drop_constraint(None, 'project_skills', type_='foreignkey')
    op.create_foreign_key(None, 'project_skills', 'repo_stats', ['repo_stat_id'], ['id'])
    op.create_foreign_key(None, 'project_skills', 'skills', ['skill_id'], ['id'])
    op.drop_constraint('uq_project_skill', 'project_skills', type_='unique')
    # ### end Alembic commands ###
