"""Tests for evidence persistence orchestration."""

from __future__ import annotations

from datetime import date, datetime

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from artifactminer.db import Base
from artifactminer.db.models import ProjectEvidence, RepoStat
from artifactminer.evidence.models import EvidenceItem
from artifactminer.evidence.orchestrator import (
    MAX_AUTOGENERATED_EVIDENCE_PER_RUN,
    persist_generated_evidence,
    persist_insights_as_project_evidence,
)
from artifactminer.skills.deep_analysis import Insight


@pytest.fixture
def db_session():
    """In-memory SQLite session, created fresh per test."""
    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(bind=engine)
    session = sessionmaker(autocommit=False, autoflush=False, bind=engine)()
    yield session
    session.close()
    Base.metadata.drop_all(bind=engine)


@pytest.fixture
def repo_stat(db_session):
    rs = RepoStat(
        project_name="evidence-project",
        project_path="/tmp/evidence-project",
        is_collaborative=False,
    )
    db_session.add(rs)
    db_session.commit()
    return rs


def test_persist_generated_evidence_validation_errors(db_session, repo_stat):
    with pytest.raises(ValueError, match="db must be a SQLAlchemy Session"):
        persist_generated_evidence(
            db={"fake": "db"},
            repo_stat_id=repo_stat.id,
            evidence_items=[],
        )

    with pytest.raises(ValueError, match="RepoStat 999 does not exist"):
        persist_generated_evidence(
            db=db_session,
            repo_stat_id=999,
            evidence_items=[],
        )

    with pytest.raises(ValueError, match="max_items must be >= 0"):
        persist_generated_evidence(
            db=db_session,
            repo_stat_id=repo_stat.id,
            evidence_items=[],
            max_items=-1,
        )


def test_persist_generated_evidence_dedupes_existing_and_batch(db_session, repo_stat):
    existing = ProjectEvidence(
        repo_stat_id=repo_stat.id,
        type="evaluation",
        content="API design and architecture: Mature boundaries",
        source="existing",
    )
    db_session.add(existing)
    db_session.commit()

    evidence_items = [
        EvidenceItem(
            type="evaluation",
            content="API design and architecture: Mature boundaries",
            source="duplicate of existing",
        ),
        EvidenceItem(
            type="EVALUATION",
            content="  API design and architecture:   Mature boundaries  ",
            source="same content with different spacing/case",
        ),
        EvidenceItem(
            type="evaluation",
            content="Robustness and error handling: Better failure behavior",
            source="new row",
        ),
        EvidenceItem(
            type="evaluation",
            content="Robustness and error handling: Better failure behavior",
            source="duplicate within same batch",
        ),
    ]

    created = persist_generated_evidence(
        db=db_session,
        repo_stat_id=repo_stat.id,
        evidence_items=evidence_items,
    )

    assert len(created) == 1
    all_rows = (
        db_session.query(ProjectEvidence)
        .filter(ProjectEvidence.repo_stat_id == repo_stat.id)
        .all()
    )
    assert len(all_rows) == 2


def test_persist_generated_evidence_enforces_max_insert_cap(db_session, repo_stat):
    evidence_items = [
        EvidenceItem(type="evaluation", content=f"Evidence row {idx}", source=f"s{idx}")
        for idx in range(MAX_AUTOGENERATED_EVIDENCE_PER_RUN + 10)
    ]

    created = persist_generated_evidence(
        db=db_session,
        repo_stat_id=repo_stat.id,
        evidence_items=evidence_items,
    )

    assert len(created) == MAX_AUTOGENERATED_EVIDENCE_PER_RUN
    assert (
        db_session.query(ProjectEvidence)
        .filter(ProjectEvidence.repo_stat_id == repo_stat.id)
        .count()
        == MAX_AUTOGENERATED_EVIDENCE_PER_RUN
    )


def test_persist_insights_as_project_evidence_maps_and_persists(db_session, repo_stat):
    created = persist_insights_as_project_evidence(
        db=db_session,
        repo_stat_id=repo_stat.id,
        insights=[
            Insight(
                title="Complexity awareness",
                evidence=["capped workers", "chunked tasks"],
                why_it_matters="Controls runtime costs.",
            )
        ],
        repo_last_commit=datetime(2025, 8, 1, 15, 30, 0),
    )

    assert len(created) == 1
    row = (
        db_session.query(ProjectEvidence)
        .filter(ProjectEvidence.repo_stat_id == repo_stat.id)
        .first()
    )
    assert row is not None
    assert row.type == "evaluation"
    assert row.content == "Complexity awareness: Controls runtime costs."
    assert row.source == "capped workers; chunked tasks"
    assert row.date == date(2025, 8, 1)


def test_persist_generated_evidence_commit_false_rollback(db_session, repo_stat):
    persist_generated_evidence(
        db=db_session,
        repo_stat_id=repo_stat.id,
        evidence_items=[EvidenceItem(type="evaluation", content="temp", source=None)],
        commit=False,
    )

    db_session.rollback()

    assert (
        db_session.query(ProjectEvidence)
        .filter(ProjectEvidence.repo_stat_id == repo_stat.id)
        .count()
        == 0
    )
